const categories = [
  { category: 'Watches' },
  { category: 'Shoes' },
  { category: 'Glasses' },
];

const products = [
  {
    id: 1,
    image: 'assets/shoes.jpg',
    title: 'Product Title 1',
    description: 'Product description 1',
    price: '100',
    rating: Math.floor(Math.random() * 6),
    category: 'Shoes',
  },
  {
    id: 2,
    image: 'assets/feature_prod_02.jpg',
    title: 'Product Title 2',
    description: 'Product description 2',
    price: '200',
    rating: Math.floor(Math.random() * 6),
    category: 'Watches',
  },
  {
    id: 3,
    image: 'assets/category_img_01.jpg',
    title: 'Product Title 3',
    description: 'Product description 3',
    price: '300',
    rating: Math.floor(Math.random() * 6),
    category: 'Watches',
  },
  {
    id: 4,
    image: 'assets/smart_watch.jpg',
    title: 'Product Title 4',
    description: 'Product description 4',
    price: '400',
    rating: Math.floor(Math.random() * 6),
    category: 'Watches',
  },
  {
    id: 5,
    image: 'assets/category_img_02.jpg',
    title: 'Product Title shoes..',
    description: 'Product description 4',
    price: '400',
    rating: Math.floor(Math.random() * 6),
    category: 'Shoes',
  },
  {
    id: 6,
    image: 'assets/category_img_03.jpg',
    title: 'Product Title 5',
    description: 'Product description 5',
    price: '500',
    rating: Math.floor(Math.random() * 6),
    category: 'Glasses',
  },
  {
    id: 7,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 6',
    description: 'Product description 6',
    price: '600',
    rating: Math.floor(Math.random() * 6),
    category: 'Watches',
  },
  {
    id: 8,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 7',
    description: 'Product description 7',
    price: '400',
    rating: Math.floor(Math.random() * 6),
    category: 'Shoes',
  },
  {
    id: 9,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 8',
    description: 'Product description 8',
    price: '500',
    rating: Math.floor(Math.random() * 6),
    category: 'Shoes',
  },
  {
    id: 10,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 9',
    description: 'Product description 9',
    price: '600',
    rating: Math.floor(Math.random() * 6),
    category: 'Shoes',
  },
  {
    id: 11,
    image: 'assets/category_img_03.jpg',
    title: 'Product Title 10',
    description: 'Product description 10',
    price: '400',
    category: 'Glasses',
  },
  {
    id: 12,
    image: 'assets/category_img_03.jpg',
    title: 'Product Title 11',
    description: 'Product description 11',
    price: '500',
    category: 'Glasses',
  },
  {
    id: 13,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 12',
    description: 'Product description 12',
    price: '600',
    category: 'Glasses',
  },
  {
    id: 14,
    image: 'assets/feature_prod_01.jpg',
    title: 'Product Title 13',
    description: 'Product description 13',
    price: '600',
    category: 'Glasses',
  },
];

export { categories, products };